version: '3'

services:

  elasticsearch:
    image: elasticsearch:7.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=example
    volumes:
      - ./.docker/elasticsearch/data:/usr/share/elasticsearch/data
      - ./logs/elasticsearch:/var/log/elasticsearch
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
      image: kibana:7.9.0
      container_name: kibana
      ports:
        - 5601:5601
      environment:
        - KIBANA_ELASTICSEARCH_URL=elasticsearch
        - ELASTICSEARCH_USERNAME=elastic
        - ELASTICSEARCH_PASSWORD=example